%YAML:1.0
timerDelay: 10
isRunning: 0
autoAdaptLog: 0
autoAdaptProfiler: 0
profilerExpandDepth: 0
popAllWindows: 1
presetCameraNumber: [0, 0, 1, 1]
presetStepName:
   -rawImage
   -foregroundMask
   -rawImage
   -foregroundMask
