%YAML:1.0
MaximumTimeLostInDoorArea: 9
TrackingMaximumTimeLost: 3
TrackingMinimumLifeSpan: 7
distanceToCameraMargin: 15
evalPrecisionThreshold: 50
hasGroundTruth: 0
highOccupancyThreshold: 2147483647
historyLength: 1800
isDebug: 0
lowOccupancyThreshold: 2147483647
lowestDistanceOverFloor: 194
maxRecursionDepth: 10
minimalHeadArea: 225
minimalHumanArea: 2500
nCameras: 1
runFromFile: 0
useKinect: 1
TrackingMaximumDistance: 2500.
headHeightMargin: 7.
highQueThreshold: 6.6666666666666663e-01
lowQueThreshold: 3.3333333333333331e-01
maxSplineSegmentLength: 5.
splineLengthThreshold: 600.
velocityScaleFactor: 2.
webServerUrl: "http://api.densekitchen.bloip.se/api/roomstate/1"
Analytics:
   - FlowEstimator
   - QueDetector
   - QueSeverityEstimator
ImageProcessor:
   - KinectSegmentation
   - TrackingBruteForce
   - EntryExitCounter
cameraPaths:
   - "/Users/gustavhager/Desktop/TSBB11/project/data/seq9/seq9-4.mp4"
entryExitGroundTruthPaths:
   - "../seq9/seq9-3.yml"
trackerGroundTruthPaths:
   - "/Users/gustavhager/Desktop/TSBB11/project/data/seq9/seq9-4GT.xml"
videoFilePaths:
   - "../data/seq10/seq10-3.mp4"
