%YAML:1.0
hasGroundTruth: 0
isDebug: 1
runFromFile: 1
useKinect: 0
nCameras: 1
evalPrecisionThreshold: 50
TrackingMaximumDistance: 2500.0
TrackingMinimzumLifeSpan: 10
TrackingMaximumTimeLost: 10
webServerUrl: "http://api.densekitchen.bloip.se/api/roomstate/1"
ImageProcessor:
   - KinectSegmentation
   - TrackingBruteForce
Analytics:
   - EntryExitCounter
   - FlowEstimator
   - QueDetector
   - QueSeverityEstimator
Evaluation:
   - EntryExitEvaluator
cameraPaths:
   - "/Users/gustavhager/Desktop/TSBB11/project/data/seq9/seq9-4.mp4"
videoFilePaths:
   - "../data/seq9/seq9-3.mp4"
trackerGroundTruthPaths:
  - "/Users/gustavhager/Desktop/TSBB11/project/data/seq9/seq9-4GT.xml"
entryExitGroundTruthPaths:
  - "../seq9/seq9-3.yml"
