%YAML:1.0
MaximumTimeLostInDoorArea: 7
TrackingMaximumTimeLost: 100
TrackingMinimumLifeSpan: 5
distanceToCameraMargin: 15
evalPrecisionThreshold: 50
hasGroundTruth: 0
highOccupancyThreshold: 2147483647
historyLength: 1800
isDebug: 1
lowOccupancyThreshold: 2147483647
lowestDistanceOverFloor: 179
maxRecursionDepth: 10
minimalHeadArea: 4005
minimalHumanArea: 3000
nCameras: 1
runFromFile: 0
useKinect: 1
TrackingMaximumDistance: 2500.
headHeightMargin: 7.
highQueThreshold: 6.6666666666666663e-01
lowQueThreshold: 3.3333333333333331e-01
maxSplineSegmentLength: 5.
splineLengthThreshold: 600.
velocityScaleFactor: 1.5000000000000000e+00
webServerUrl: "http://api.densekitchen.bloip.se/api/roomstate/1"
Analytics:
   - FlowEstimator
   - QueDetector
   - QueSeverityEstimator
ImageProcessor:
   - KinectSegmentation
   - TrackingBruteForce
   - EntryExitCounter
cameraPaths:
   - "../data/seq9/seq9-3.mp4"
entryExitGroundTruthPaths:
   - "../data/seq9/seq9-3.yml"
trackerGroundTruthPaths:
   - /Users/gustavhager/Desktop/TSBB11/project/data/GTseq14
videoFilePaths:
   - "/Users/Niko/Dropbox/Liu/TSBB11/Dense Kitchen/seq9-4/seq9-4.mp4"
