%YAML:1.0
MaximumTimeLostInDoorArea: 9
TrackingMaximumTimeLost: 100
TrackingMinimumLifeSpan: 7
distanceToCameraMargin: 15
evalPrecisionThreshold: 50
hasGroundTruth: 0
highOccupancyThreshold: 2147483647
historyLength: 1800
isDebug: 0
lowOccupancyThreshold: 2147483647
lowestDistanceOverFloor: 57
maxRecursionDepth: 10
minimalHeadArea: 225
minimalHumanArea: 2500
nCameras: 1
runFromFile: 1
useKinect: 0
TrackingMaximumDistance: 2500.
headHeightMargin: 7.
highQueThreshold: 6.6666666666666663e-001
lowQueThreshold: 3.3333333333333331e-001
maxSplineSegmentLength: 5.
splineLengthThreshold: 600.
velocityScaleFactor: 2.
webServerUrl: "http://api.densekitchen.bloip.se/api/roomstate/1"
Analytics:
   - FlowEstimator
   - QueDetector
   - QueSeverityEstimator
ImageProcessor:
   - KinectSegmentation
   - TrackingBruteForce
   - EntryExitCounter
   - EntryExitEvaluator
cameraPaths:
   - "../data/seq9/seq9-3.mp4"
entryExitGroundTruthPaths:
   - "../data/seq9/seq9-3.yml"
trackerGroundTruthPaths:
   - /Users/gustavhager/Desktop/TSBB11/project/data/GTseq14
videoFilePaths:
   - "../data/seq12/seq12.mp4"
